# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 02:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='city')),
                ('area_code', models.CharField(max_length=20, verbose_name='area_code')),
                ('flag', models.BooleanField(default=True, verbose_name='flag')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'city information',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50, verbose_name='district')),
                ('remark', models.TextField(verbose_name='remark')),
                ('flag', models.BooleanField(default=True, verbose_name='flag')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.City', verbose_name='city')),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'district information',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2, verbose_name='sex')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('image', models.ImageField(blank=True, null=True, upload_to='icon//%Y%m%d', verbose_name='icon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50, verbose_name='region')),
                ('flag', models.BooleanField(default=True, verbose_name='flag')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'region information',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Region', verbose_name='region'),
        ),
    ]
